### PR TITLE
fix: validate all schemas in actor.json

### LINKED ISSUE #1036: 'apify validate-schema' should validate all schemas in actor.json, not just input_schema

### PR DESCRIPTION
**Pull request by l2ysho**
example output

```
Info: Validating input schema at .actor/input_schema.json
Success: Input schema is valid.
Info: Validating Dataset schema at .actor/dataset_schema.json
Success: Dataset schema is valid.
Info: Validating Output schema at actor/output_schema.json
Success: Output schema is valid.
Info: Validating Key-Value Store schema at .actor/key_value_store_schema.json
Success: Key-Value Store schema is valid.
```
closes #1036

### CODE REVIEW

File: src/commands/validate-schema.ts [hunk 1]
```diff
@@ -35,22 +47,116 @@ Optionally specify custom schema path to validate.`;
 	static override args = {
 		path: Args.string({
 			required: false,
-			description: 'Optional path to your INPUT_SCHEMA.json file. If not provided ./INPUT_SCHEMA.json is used.',
+			description:
+				'Optional path to your INPUT_SCHEMA.json file. If not provided, validates all schemas in actor.json.',
```
Comment (vladfrangu) [inline src/commands/validate-schema.ts]:
```suggestion
				`Optional path to your INPUT_SCHEMA.json file. If not provided, validates all schemas in '${LOCAL_CONFIG_PATH}'.`,
```

**Review by vladfrangu — APPROVED** [review]
Optional
