### PR TITLE
fix: Set correct exit code on incorect `apify secrets` usage

### LINKED ISSUE #953: Calling `apify secrets add` without arguments results in exit code 0
- As mentioned in the title - calling `apify secrets add` without arguments results in exit code 0
- The expected result is a non-zero exit code
- Since the command calls `addSecret` which throws an `Error`, there's a good chance that this is not properly handled for any command

### PR DESCRIPTION
**Pull request by janbuchar**
- closes #953

### CODE REVIEW

File: src/lib/command-framework/apify-command.ts [hunk 1]
```diff
@@ -588,9 +590,15 @@ export abstract class ApifyCommand<T extends typeof BuiltApifyCommand = typeof B
...
-			showUsageString: true,
-		});
+		let help: string | undefined;
+
+		try {
+			help = selectiveRenderHelpForCommand(this.ctor, {
+				showUsageString: true,
+			});
+		} catch {
+			// Help renderer may not be registered (e.g. in tests)
```
Comment (l2ysho) [inline src/lib/command-framework/apify-command.ts:600]: do we want some log.warn? cc @vladfrangu

**Review by l2ysho — APPROVED** [review]
👍 (just small nit)

File: src/lib/command-framework/apify-command.ts (hunk 1 above)
Comment (vladfrangu) [reply src/lib/command-framework/apify-command.ts:600]: 🤷 Imo we can even let it bubble up
